#!/usr/bin/env python3
"""Re-export Confluence pages listed by the Gliffy affected-pages scan."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from confluence_markdown_exporter.confluence import Page
from confluence_markdown_exporter.confluence import settings
from confluence_markdown_exporter.utils.app_data_store import set_setting
from confluence_markdown_exporter.utils.lockfile import LockfileManager


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "scan_result",
        type=Path,
        help="Path to JSON generated by scan_gliffy_affected_pages.py",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        required=True,
        help="Export root to write Markdown and attachments into",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Optional limit for dry runs or partial batches",
    )
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    payload = json.loads(args.scan_result.read_text())
    pages = payload.get("pages") or payload.get("verified_pages") or []
    if args.limit is not None:
        pages = pages[: args.limit]

    output_root = args.output_root
    set_setting("export.output_path", output_root)
    settings.export.output_path = output_root

    LockfileManager.init()

    results: list[dict[str, str | bool]] = []
    failed_count = 0
    for page_info in pages:
        page_id = str(page_info["page_id"])
        try:
            page = Page.from_id(int(page_id))
            page.export()
            LockfileManager.record_page(page)
        except Exception as exc:  # noqa: BLE001
            failed_count += 1
            results.append(
                {
                    "page_id": page_id,
                    "title": str(page_info.get("title", "")),
                    "export_path": "",
                    "success": False,
                    "error": f"{type(exc).__name__}: {exc}",
                }
            )
            continue

        results.append(
            {
                "page_id": page_id,
                "title": page.title,
                "export_path": str(output_root / page.export_path),
                "success": True,
            }
        )

    summary = {
        "output_root": str(output_root),
        "requested_count": len(pages),
        "exported_count": len([result for result in results if result["success"]]),
        "failed_count": failed_count,
        "pages": results,
    }
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
