#!/usr/bin/env python3
"""Verify Gliffy candidates via Confluence page content and attachment metadata."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from confluence_markdown_exporter.confluence import Page


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "scan_result",
        type=Path,
        help="Path to JSON generated by scan_gliffy_affected_pages.py",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Optional path to write JSON results",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Optional limit for partial verification",
    )
    return parser


def is_verified_gliffy(page: Page) -> tuple[bool, list[str]]:
    reasons: list[str] = []
    attachment_comments = {attachment.comment.upper() for attachment in page.attachments}
    if any("GLIFFY" in comment for comment in attachment_comments):
        reasons.append("attachment_comment_contains_gliffy")
    if "gliffy-container" in page.body or "plugins/gliffy" in page.body:
        reasons.append("body_contains_gliffy_markup")
    if "gliffy-container" in page.body_export or "plugins/gliffy" in page.body_export:
        reasons.append("export_view_contains_gliffy_markup")
    return bool(reasons), reasons


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    payload = json.loads(args.scan_result.read_text())
    pages = payload.get("pages", [])
    if args.limit is not None:
        pages = pages[: args.limit]

    verified: list[dict[str, object]] = []
    rejected: list[dict[str, object]] = []

    for page_info in pages:
        page_id = int(page_info["page_id"])
        page = Page.from_id(page_id)
        matched, reasons = is_verified_gliffy(page)
        item = {
            "page_id": str(page.id),
            "title": page.title,
            "reasons": reasons,
        }
        if matched:
            verified.append(item)
        else:
            rejected.append(item)

    result = {
        "requested_count": len(pages),
        "verified_count": len(verified),
        "rejected_count": len(rejected),
        "verified_pages": verified,
        "rejected_pages": rejected,
    }

    rendered = json.dumps(result, ensure_ascii=False, indent=2)
    if args.output:
        args.output.write_text(rendered)
    print(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
